# Generated by Django 4.2.5 on 2023-09-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EFOTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.CharField(max_length=200, unique=True)),
                ('label', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='EFOTermSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=300)),
                ('efo_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.efoterm')),
            ],
            options={
                'unique_together': {('efo_term', 'synonym')},
            },
        ),
        migrations.CreateModel(
            name='EFOTermOntology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_efo_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='api.efoterm')),
                ('parent_efo_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='api.efoterm')),
            ],
            options={
                'unique_together': {('parent_efo_term', 'child_efo_term')},
            },
        ),
    ]
